modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/Octo-Studios/yagm/issues"


[[mods]]
modId = "yagm"
version = "0.1"
displayName = "Yet Another Gravestone Mod"
authors = "SSKirillSS"
logoFile = "logo.png"

[[dependencies.yagm]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yagm]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yagm]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.yagm]]
modId = "curios"
type = "optional"
versionRange = "[9.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yagm]]
modId = "accessories"
type = "optional"
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "yagm.mixins.json"
[[mixins]]
config = "yagm-common.mixins.json"